package com.randomNumberGenerator;
import java.util.Scanner;

//By: Faizabahmed Saiyed
//Date: 13-April-2023
//Type: Mini Project
//Objective: revising java concepts
//Refrance: Apna College.yt
//Function: Guess the number which is generated by system

public class Main {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        int myNum = (int)(Math.random()*100);
        int userNumber = 0;
        do {
            System.out.println("Guess the number: ");
            userNumber = sc.nextInt();

            if(userNumber == myNum){
                System.out.println("Correct");
                break;
            }
            else if(userNumber > myNum){
                System.out.println("Your number is large");
            }
            else {
                System.out.println("Your number is small");
            }

        } while(userNumber >= 0);

        System.out.println("My number was: ");
        System.out.println(myNum);


    }
}
